/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.Random;

import org.junit.Test;

import io.github.jehuipark.polling.core.Builder;
import io.github.jehuipark.polling.core.PollingManager;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    	long LIFE_TIME = 10000;
    	long TRANSACTION = 5000;
    	long INTERVAL = 100;
    	
    	PollingManager pollingManager = PollingManager.Lazy.INSTANCE;
    	Builder<Integer> builder = new Builder<>();
    	builder.setInterval(INTERVAL)
    	.setTransactionTime(TRANSACTION)
    	.setObserve(()->{
    		return new Random().nextInt(3);
    	})
    	.setValidation((value, origin)->{
    		boolean isUpdate = false;
    		if(value != origin)
    			isUpdate = true;
			return isUpdate;
    	});
    	
    	pollingManager.start("id", LIFE_TIME, builder);
    }
}

